### ISSUE TITLE
Do we ignore "npx cap sync"?

### ISSUE THREAD

**Issue by kalnode** [arzyu/capacitor-sync-version#3]
Hey, this plugin works well! thx

Just want to affirm, that in using this plugin, you would always use `capacitor-sync-version android ios` instead of the regular Capacitor sync command (which in my setup, is `npx cap sync`)?

I didn't see an explicit statement on this in the readme.

**Comment by arzyu** [comment]
According to [the document of the `cap sync`](https://capacitorjs.com/docs/cli/commands/sync), `cap sync` is a compound command, which is equivalent to running `cap copy` followed by `cap update`. So we can just hook `capacitor:copy:before` like below and it will work fine.

```json
{
  "scripts": {
    "capacitor:copy:before": "capacitor-sync-version"
  }
}
```

**Comment by kalnode** [comment]
Ok that's what I got. So I guess the answer is yes. =P

It works well so far!
